### ISSUE TITLE
getFormattedCatalogDisplayImagesForCollectionItem() 404Not found bug

### ISSUE THREAD

**Issue by jwcha1030** [jwcha1030/CS416_GroupProject#16]
I got 404 Not found bug as shown below:
<img width="365" alt="Screen Shot 2020-12-24 at 11 54 12 PM" src="https://user-images.githubusercontent.com/42469606/103095425-e7c2f980-4643-11eb-8cfe-9d2cda847bc2.png">

I am calling *getFormattedCatalogDisplayImagesForCollectionItem()* API call while calling *hasCollectionItemCatalogDisplay()* API. See the code below for details:

*hasCollectionItemCatalogDisplay* call is done first in the *checkAndFetchCatalogImages* function.
<img width="773" alt="Screen Shot 2020-12-24 at 11 59 01 PM" src="https://user-images.githubusercontent.com/42469606/103095547-49836380-4644-11eb-80ed-83057ec06f3e.png">

Note that *fetchCatalogImages(cd_id)* is the API call for *getFormattedCatalogDisplayImagesForCollectionItem*:
<img width="795" alt="Screen Shot 2020-12-24 at 11 59 13 PM" src="https://user-images.githubusercontent.com/42469606/103095600-818aa680-4644-11eb-9191-838086e48ad0.png">

**Comment by jwcha1030** [comment]
Let me know if the nested API call is the cause of the error.

**Comment by Habced** [comment]
i had a url typo. fixed

**Comment by jwcha1030** [comment]
Unhandled rescode error when calling getFormattedCatalogDisplayImagesForCollectionItem
