### ISSUE TITLE
AddCollectionItem Rescode=0 error

### ISSUE THREAD

**Issue by jwcha1030** [jwcha1030/CS416_GroupProject#20]
I am getting a rescode error. The input is as follows:

<img width="368" alt="Screen Shot 2021-01-08 at 12 16 43 AM" src="https://user-images.githubusercontent.com/42469606/103909579-3a71da80-5147-11eb-863c-0fd484d71b58.png">

if there are no galImages 2~6 uploaded by the admins, the input is passed as a "" (blank string).

**Comment by Habced** [comment]
Do you still get this error?

**Comment by jwcha1030** [comment]
<img width="382" alt="Screen Shot 2021-01-12 at 1 32 31 PM" src="https://user-images.githubusercontent.com/42469606/104269872-a1421b80-54da-11eb-9982-f4941dae41d9.png">
yes I am still getting the error

**Comment by jwcha1030** [comment]
Fixed and working fine it seems
