### ISSUE TITLE
editAllCollectionItemCatalogDisplayImage rescode=0 error

### ISSUE THREAD

**Issue by jwcha1030** [jwcha1030/CS416_GroupProject#21]
I am getting a rescode error when I append new images to the previously fetched images. The input is as follows:
<img width="362" alt="Screen Shot 2021-01-07 at 10 48 44 PM" src="https://user-images.githubusercontent.com/42469606/103910013-b10ed800-5147-11eb-9646-cfa2b4bf69a0.png">

(EDIT)I have mentioned in our group chat; will you add a function that checks previously added images (i.e., those that are in URL)?

Also uploading images (Object File) to an empty catalog object returns rescode=0. Below is the sequence of processes for the test:
<img width="802" alt="Screen Shot 2021-01-08 at 12 28 34 AM" src="https://user-images.githubusercontent.com/42469606/103910808-9ab54c00-5148-11eb-8856-9d0a92e3f718.png">

<img width="1792" alt="Screen Shot 2021-01-08 at 12 30 24 AM" src="https://user-images.githubusercontent.com/42469606/103910940-c59fa000-5148-11eb-9fce-31acaecee13e.png">
<img width="1792" alt="Screen Shot 2021-01-08 at 12 31 17 AM" src="https://user-images.githubusercontent.com/42469606/103911001-dc45f700-5148-11eb-8309-50a67722a127.png">

**Comment by Habced** [comment]
fixed the url issue. 

for the "empty catalog object" one have you called hasCollectionItemCatalogDisplay to check if it has a catalog display? or do you want me to automatically create one if it doesn't exist (please specify which calls you want this to be applied to if you want it this way)?

**Comment by jwcha1030** [comment]
once I add a catalog image the hasCollectionItemCatalogDisplay returns >0 (hence pops up an edit 360 view modal). If I remove all the images and submit, hasCollection still returns >1; hence, it does not check if the catalog object is empty. It is fine as it is. 

The problem I am having is deleting item(s) and submitting an empty or updated object file via editAllCollectionItemCatalogDisplayImage() return success, but the new object file is not updated when I fetch after a refresh.

**Comment by Habced** [comment]
I updated the logic in editAllColItemCatDisImage, hopefully it works more consistently now. Lmk how it goes with the testing

**Comment by jwcha1030** [comment]
Seems to be working great now.
